version: '3.9'

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command: sh -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

volumes:
  pgdata: